services:
  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ${HOME}/.local/share/gh/extensions/gh-d3nw/web/:/usr/share/nginx/html/:rw
      - ${PWD}/data.json:/usr/share/nginx/html/data.json:ro
