services:
  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ${PWD}/docs/:/usr/share/nginx/html/
      - ${PWD}/data.json:/usr/share/nginx/html/data.json
      - ${PWD}/config.json:/usr/share/nginx/html/config.json
