#!/bin/sh
set -e


CMD=$(basename $0 | tr '-' ' ')
if [ "$#" -eq 0 ]; then
    echo "Usage:"
    echo " $CMD install"
    echo " $CMD up"
    echo " $CMD down"
    echo " $CMD shell"
    exit 1
fi

TOP=$(dirname "$0")

if [ "$1" = "up" ]; then
  docker compose -f ${TOP}/docker-compose.yml --env-file .env up -d
  exit 0
fi

if [ "$1" = "down" ]; then
  docker compose -f ${TOP}/docker-compose.yml --env-file .env down
  exit 0
fi

if [ "$1" = "shell" ]; then
  docker exec -it web sh
  exit 0
fi

if [ "$1" = "install" ]; then
  # If not exist docs
  if [ ! -d docs ]; then
    cp -rf ${TOP}/docs .
  fi
  # If not exist data.json
  if [ ! -e data.json ]; then
    ln -sf ./docs/data.json .
  fi
  if [ ! -e config.json ]; then
    ln -s ./docs/config.json .
  fi
  # If not exist .env
  if [ ! -f .env ]; then
    touch .env
  fi
  mkdir -p docs/logo
  # Install service logo
  wget -nv https://upload.wikimedia.org/wikipedia/commons/8/8a/Jira_Logo.svg -O ./docs/logo/jira.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/8/88/Atlassian_Confluence_2017_logo.svg -O ./docs/logo/confluence.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/3/35/GitLab_icon.svg -O ./docs/logo/gitlab.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg -O ./docs/logo/github.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/b/b9/Slack_Technologies_Logo.svg -O ./docs/logo/slack.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/1/12/Rocket.Chat_Logo.svg -O ./docs/logo/rocketchat.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/b/b8/YouTube_Logo_2017.svg -O ./docs/logo/youtube.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/9/95/Instagram_logo_2022.svg -O ./docs/logo/instagram.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/c/ce/X_logo_2023.svg -O ./docs/logo/x.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/3/3b/Grafana_icon.svg -O ./docs/logo/grafana.svg
  exit 0
fi
echo "Invalid option: $1"
exit 1
