#!/bin/sh
set -e


CMD=$(basename $0 | tr '-' ' ')
if [ "$#" -eq 0 ]; then
    echo "Usage:"
    echo " $CMD install"
    echo " $CMD up"
    echo " $CMD down"
    echo " $CMD shell"
    exit 1
fi

TOP=$(dirname "$0")

if [ "$1" = "up" ]; then
  docker compose -f ${TOP}/docker-compose.yml --env-file .env up -d
  exit 0
fi

if [ "$1" = "down" ]; then
  docker compose -f ${TOP}/docker-compose.yml --env-file .env down
  exit 0
fi

if [ "$1" = "shell" ]; then
  docker exec -it web sh
  exit 0
fi

if [ "$1" = "install" ]; then
  # If not exist data.json
  if [ ! -f data.json ]; then
    cp ${TOP}/data.json .
  fi
  # If not exist .env
  if [ ! -f .env ]; then
    touch .env
  fi
  # Install service logo
  wget -nv https://upload.wikimedia.org/wikipedia/commons/8/8a/Jira_Logo.svg -O $TOP/web/jira.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/8/88/Atlassian_Confluence_2017_logo.svg -O $TOP/web/confluence.svg
  wget -nw https://upload.wikimedia.org/wikipedia/commons/3/35/GitLab_icon.svg -O $TOP/web/gitlab.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg -O $TOP/web/github.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/b/b9/Slack_Technologies_Logo.svg -O $TOP/web/slack.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/1/12/Rocket.Chat_Logo.svg -O $TOP/rocketchat.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/b/b8/YouTube_Logo_2017.svg -O $TOP/youtube.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/9/95/Instagram_logo_2022.svg -O $TOP/instagram.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/c/ce/X_logo_2023.svg -O $TOP/x.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/3/3b/Grafana_icon.svg -O $TOP/grafana.svg
  exit 0
fi

echo "Invalid option: $1"
exit 1
