#!/bin/bash
if [ "$#" -ne 1 ]; then
  echo "Usage:"
  echo " $0 up"
  echo " $0 down"
  echo " $0 shell"
  echo " $0 install-logo"
  exit 1
fi

if [ "$1" = "up" ]; then
  docker compose up -d
  exit 0
fi
if [ "$1" = "down" ]; then
  docker compose down
  exit 0
fi
if [ "$1" = "build" ]; then
  docker compose build
  exit 0
fi
if [ "$1" = "shell" ]; then
  docker exec -it web sh
  exit 0
fi
if [ "$1" = "install-logo" ]; then
  wget -nv https://upload.wikimedia.org/wikipedia/commons/8/8a/Jira_Logo.svg -O web/jira.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/8/88/Atlassian_Confluence_2017_logo.svg -O web/confluence.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/e/e1/GitLab_logo.svg -O web/gitlab.svg
  wget -nv https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg -O web/github.svg
  exit 0
fi

echo "Invalid option: $1"
exit 1

