FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY main.js /usr/share/nginx/html/main.js
COPY data.json /usr/share/nginx/html/data.json
COPY dataLoader.js /usr/share/nginx/html/dataLoader.js
