FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY main.js /usr/share/nginx/html/main.js
COPY data.csv /usr/share/nginx/html/data.csv
COPY dataLoader.js /usr/share/nginx/html/dataLoader.js
